package com.example.enums;

public enum MatTypes {
    ORIGINAL_MAT,
    BINARIZED_MAT,
    BINARIZED_MAT_WITHOUT_EMPTY_SPACES_AND_SMALL_OBJECTS,
    CONTOURIZED_MAT_FILLED,
    CONTOURIZED_MAT_NOT_FILLED,
    DISTANCE_TRANSFORMED_MAT,
    LOCAL_MAXIMA_MAT,
    MERGED_BINARIZED_MAT_WITHOUT_SMALL_OBJECTS_WITH_LOCAL_MAXIMA_MAT,
    CONVEX_HULL_MAT,
    CONVEX_HULL_MAT_ON_SKELETON,
    CONTOURIZED_MAT_NOT_FILLED_WITH_FINGERS,
    CRITICAL_POINTS_MAT
}
